# Generated by Django 4.0.5 on 2022-07-02 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='familiar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('dni', models.IntegerField(max_length=10)),
                ('email', models.EmailField(max_length=100)),
                ('fecha_nacimiento', models.DateTimeField()),
            ],
        ),
    ]
