# Generated by Django 4.0.5 on 2022-07-11 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DatosFlia', '0002_alter_familiar_dni_alter_familiar_fecha_nacimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Electrodomestico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoE', models.CharField(max_length=40)),
                ('marcaE', models.CharField(max_length=40)),
                ('modeloE', models.CharField(max_length=40)),
                ('precio', models.IntegerField()),
                ('fecha_produccionE', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoV', models.CharField(max_length=40)),
                ('marcaV', models.CharField(max_length=40)),
                ('modeloV', models.CharField(max_length=40)),
                ('ruedas', models.IntegerField()),
                ('fecha_produccionV', models.DateField()),
            ],
        ),
    ]
